serverFiles:
  alerting_kubernetes.yml:
    groups:
      - name: KubernetesRules
        rules:
        - alert: KubeNodeNotReady
          annotations:
            message: '{{$labels.node}} has been unready for more than an hour.'
          expr: kube_node_status_condition{job="kube-state-metrics",condition="Ready",status="true"} == 0
          for: 1h
          labels:
            severity: warning
        - alert: KubeClientErrors
          annotations:
            message: 'Kubernetes API server client {{$labels.job}} {{$labels.instance}} is experiencing {{ printf "%0.0f" $value }}% errors.'
          expr: |-
            (sum(rate(rest_client_requests_total{code=~"5.."}[5m])) by (instance, job)
              /
            sum(rate(rest_client_requests_total[5m])) by (instance, job))
            * 100 > 1
          for: 15m
          labels:
            severity: warning
        - alert: KubeletTooManyPods
          annotations:
            message: 'Kubelet {{ $labels.instance }} is running {{ $value }} Pods, close to the limit of 110.'
          expr: kubelet_running_pod_count{job="kubelet"} > 110 * 0.9
          for: 15m
          labels:
            severity: warning
        - alert: KubeAPILatencyHigh
          annotations:
            message: 'The API server has a 99th percentile latency of {{ $value }} seconds for {{ $labels.verb }} {{ $labels.resource }}.'
          expr: cluster_quantile:apiserver_request_latencies:histogram_quantile{job="apiserver",quantile="0.99",subresource!="log",verb!~"^(?:LIST|WATCH|WATCHLIST|PROXY|CONNECT)$"} > 1
          for: 10m
          labels:
            severity: warning
        - alert: KubeAPIErrorsHigh
          annotations:
            message: 'API server is returning errors for {{ $value }}% of requests.'
          expr: |-
            sum(rate(apiserver_request_count{job="apiserver",code=~"^(?:5..)$"}[5m]))
              /
            sum(rate(apiserver_request_count{job="apiserver"}[5m])) * 100 > 3
          for: 10m
          labels:
            severity: critical
        - alert: KubeAPIErrorsHigh
          annotations:
            message: 'API server is returning errors for {{ $value }}% of requests.'
          expr: |-
            sum(rate(apiserver_request_count{job="apiserver",code=~"^(?:5..)$"}[5m]))
              /
            sum(rate(apiserver_request_count{job="apiserver"}[5m])) * 100 > 1
          for: 10m
          labels:
            severity: warning
        - alert: KubeAPIErrorsHigh
          annotations:
            message: 'API server is returning errors for {{ $value }}% of requests for {{ $labels.verb }} {{ $labels.resource }} {{ $labels.subresource }}.'
          expr: |-
            sum(rate(apiserver_request_count{job="apiserver",code=~"^(?:5..)$"}[5m])) by (resource,subresource,verb)
              /
            sum(rate(apiserver_request_count{job="apiserver"}[5m])) by (resource,subresource,verb) * 100 > 10
          for: 10m
          labels:
            severity: critical
        - alert: KubeAPIErrorsHigh
          annotations:
            message: 'API server is returning errors for {{ $value }}% of requests for {{ $labels.verb }} {{ $labels.resource }} {{ $labels.subresource }}.'
          expr: |-
            sum(rate(apiserver_request_count{job="apiserver",code=~"^(?:5..)$"}[5m])) by (resource,subresource,verb)
              /
            sum(rate(apiserver_request_count{job="apiserver"}[5m])) by (resource,subresource,verb) * 100 > 5
          for: 10m
          labels:
            severity: warning
        - alert: KubeClientCertificateExpiration
          annotations:
            message: 'A client certificate used to authenticate to the apiserver is expiring in less than 7.0 days.'
          expr: apiserver_client_certificate_expiration_seconds_count{job="apiserver"} > 0 and histogram_quantile(0.01, sum by (job, le) (rate(apiserver_client_certificate_expiration_seconds_bucket{job="apiserver"}[5m]))) < 604800
          labels:
            severity: warning
        - alert: KubeClientCertificateExpiration
          annotations:
            message: 'A client certificate used to authenticate to the apiserver is expiring in less than 24.0 hours.'
          expr: apiserver_client_certificate_expiration_seconds_count{job="apiserver"} > 0 and histogram_quantile(0.01, sum by (job, le) (rate(apiserver_client_certificate_expiration_seconds_bucket{job="apiserver"}[5m]))) < 86400
          labels:
            severity: critical
